<?php

return [
    1 => [
        'ALAWIHAO',
        'AWITAN',
        'BAGASBAS',
        'BARANGAY I',
        'BARANGAY II',
        'BARANGAY III',
        'BARANGAY IV',
        'BARANGAY V',
        'BARANGAY VI',
        'BARANGAY VII',
        'BARANGAY VIII',
        'BIBIRAO',
        'BORABOD',
        'CALASGASAN',
        'CAMAMBUGAN',
        'COBANGBANG',
        'DOGONGAN',
        'GAHONON',
        'GUBAT',
        'LAG-ON',
        'MAGANG',
        'MAMBALITE',
        'MANCRUZ',
        'PAMORANGON',
        'SAN ISIDRO'
    ],
    2 => [
        'AGUIT-IT',
        'BANOCBOC',
        'BARANGAY I',
        'BARANGAY II',
        'BARANGAY III',
        'CAGBALOGO',
        'CALANGCAWAN NORTE',
        'CALANGCAWAN SUR',
        'GUINACUTAN',
        'MANGCAWAYAN',
        'MANGCAYO',
        'MANLUCUGAN',
        'MATANGO',
        'NAPILIHAN',
        'PINAGTIGASAN',
        'SABANG',
        'SANTO DOMINGO',
        'SINGI',
        'SULA'
    ],
    3 => [
        'AWITAN',
        'BAGUMBAYAN',
        'BAKAL',
        'BATOBALANI',
        'CALABURNAY',
        'CAPACUAN',
        'CASALUGAN',
        'DAGANG',
        'DALNAC',
        'DANCALAN',
        'GUMAUS',
        'LABNIG',
        'MACOLABO ISLAND',
        'MALACBANG',
        'MALAGUIT',
        'MAMPUNGO',
        'MANGKASAY',
        'MAYBATO',
        'PALANAS',
        'PINAGBIRAYAN MALAKI',
        'PINAGBIRAYAN MUNTI',
        'POBLACION NORTE',
        'POBLACION SUR',
        'TABAS',
        'TALUSAN',
        'TAWIG',
        'TUGOS'
    ],
];
