<?php

namespace App\Services\Profile;

use App\Repositories\User\UserRepository;
use App\Services\BaseService;

use App\Services\Ticket\TicketFacade;
use App\User;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class ProfileService extends BaseService
{
    use ValidatesRequests;

    const LOGS_CREATING = 'CREATING PROFILE:';
    const LOGS_DELETING = 'DELETING PROFILE:';

    protected $userRepository;

    public function __construct(UserRepository $userRepository){
        $this->userRepository = $userRepository;
    }

    public function update($request){
        $param = $request->all();
        if(Auth::user()->user_type == 'user'){
            $this->validate($request, [
                'phone' => [
                    'required',
                    Rule::unique('users')->ignore(Auth::id()),
                ],
                'country_of_residence' => 'required',
                'address' => 'required|regex:/^[a-zA-Z0-9\d\-_.,#\s]+$/u',
                'city' => 'required|regex:/^[a-zA-Z0-9\d\-_.,\s]+$/u|max:100',
                'state' => 'required|regex:/^[a-zA-Z0-9\d\-_.,\s]+$/u|max:100',
                'zip' => 'required|max:20',
                'profile_picture' => 'nullable|max:5120|mimes:jpeg,jpg,bmp,png,gif,JPG,JPEG',
            ], [
                'address.regex'=> _lang('Address must be in english characters (a-z,A-Z,0-9,.,-,#)'),
                'city.regex'=> _lang('City must be in english characters (a-z,A-Z)'),
                'state.regex'=> _lang('State must be in english characters (a-z,A-Z)'),
            ]);
        }else{
            $this->validate($request, [
                'phone' => [
                    'required',
                    Rule::unique('users')->ignore(Auth::id()),
                ],
                'profile_picture' => 'nullable|image|max:5120',
            ]);
        }

        if ($request->hasFile('profile_picture')){
            $image = $request->file('profile_picture');
            $file_name = "profile_".time().'.'.$image->getClientOriginalExtension();
            $image->move(public_path('uploads/profile/'),$file_name);
            $param['profile_picture'] = $file_name;
        }

        if( isset($request->others) ){
            $param['others'] = serialize($request->others);
        }

        $user = $this->userRepository->update(Auth::id(),$param);
        $message = $user ? 'Profile updated successfully' : "An error occurred please try again";
        return back()->with('success', _lang($message));
    }

    public function requestForChangeNameOrDateOfBirth($request){
        if (!$request->first_name && !$request->last_name && !strtotime($request->date_of_birth)) {
            return response()->json([
                    'result' => 'error',
                    'message' => 'Unable to process request.',
            ]);
        }
        $param = [
            "email" => Auth::user()->email,
            "account_number" => Auth::user()->account_number,
            "name" => Auth::user()->first_name . " " . Auth::user()->last_name,
            "date_of_birth" => Auth::user()->user_information->date_of_birth,
            "first_name" => strtoupper($request->first_name),
            "last_name" => strtoupper($request->last_name),
            "new_date_of_birth" => $request->date_of_birth
        ];
        $ticketParams = [
            "department" => "customer_support",
            "subject" => "update_user_information_request",
            "message" => self::generateTicketMessage($param)
        ];
        $request->request->add($ticketParams);
        return TicketFacade::create($request);
    }

    private function generateTicketMessage($param){
        $message = "<p>". _lang("This is an autogenerated ticket from User Update Information Request. Request details are as follows:")."<br><br><b>"._lang("Member Information:")."</b></p>";
        $message.= "<p>". _lang("Email Address").": ".$param['email']."<br>"
            ._lang("Oriental Wallet Account Number:")." ".$param['account_number']."<br>"
            ._lang("Name:")." ".$param["name"]."<br>"
            ._lang("Date of Birth").": ".$param["date_of_birth"]."<br><br>";
        $message.= "<b>". _lang("Update the following to:")."</b><br></p>";
        if($param["first_name"] && $param["last_name"]){
            $message.= "<p>". _lang("First Name").": ".$param["first_name"]."</p><p>"._lang("Last Name").": ".$param["last_name"]."</p>";
        }
        if($param["new_date_of_birth"] && strtotime($param["new_date_of_birth"])){
            $message.= "<p>". _lang("Date of Birth").": ". Carbon::parse($param["new_date_of_birth"])->format('Y-m-d') ."</p>";
        }
        $message.= "<p><br>". _lang("Thank you.")."</p>";
        return $message;
    }
}
